// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.Robot2018.commands.solenoid;
import org.usfirst.frc2813.Robot2018.commands.GearheadsInstantCommand;
import org.usfirst.frc2813.logging.LogType;
import org.usfirst.frc2813.logging.Logger;

import edu.wpi.first.wpilibj.Solenoid;

/**
 *
 */
public class SimpleSolenoidToggleStateInstant extends GearheadsInstantCommand {
	/**
	 * Switch the position of the intake pistons
	 */
	private final Solenoid solenoid;

    public SimpleSolenoidToggleStateInstant(Solenoid solenoid) {
    	this.solenoid = solenoid;
    	setName(toString());
    }

	//@Override
	protected void initialize() {
		super.initialize();
        boolean old = solenoid.get();
        Logger.printFormat(LogType.INFO,"%s toggling %s from %b to %b",this,solenoid,old,!old);
        solenoid.set(!old);
	}

    public String toString() {
        return getClass().getSimpleName() + "(" + solenoid + ")";
    }
}

