// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.Robot2018.commands.Arm;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc2813.Robot2018.Direction;
import org.usfirst.frc2813.Robot2018.Robot;

/*
 * TODO: This class needs to be coded for the Talon SRX
 * Need to decide what this class is used for - SHOULD IT STILL BE USED?
 */
public class ArmLimitSwitch extends Command {
	private DigitalInput digitalInput;
	private SpeedController speedController;
	private Encoder encoder;
	private Direction direction;
	private static final double DESIRED_ENCODER_VALUE  = 1;//TODO change value

	public ArmLimitSwitch(Direction upDown) {
		direction = upDown;
		requires(Robot.arm);
	}

	// Called just before this Command runs the first time
	//@Override
	protected void initialize() {
		/*digitalInput = Robot.arm.limitSwitch;
    	speedController = Robot.arm.speedController;
    	encoder = Robot.arm.encoder;*/
	}

	protected void execute() {
		if (direction.equals(Direction.UP)) {//going up
			speedController.set(1);//TODO not sure if 1 or -1 is up
		}
		else {//going down
			speedController.set(-1);//TODO not sure if -1 or 1 is down	
		}
	}

	protected boolean isFinished() {
		if (direction.equals(Direction.UP)) {
			return digitalInput.get();
		}
		return encoder.getDistance() >= DESIRED_ENCODER_VALUE;
	}
}
