// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2813.Robot2018.subsystems;

import org.usfirst.frc2813.Robot2018.Robot;
import org.usfirst.frc2813.Robot2018.RobotMap;
import org.usfirst.frc2813.Robot2018.commands.DriveTrain.OIDrive;

import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.ctre.phoenix.motorcontrol.can.VictorSPX;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.Sendable;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class DriveTrain extends Subsystem {

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public final SpeedController speedControllerPort = RobotMap.driveTrainSpeedControllerPort;
	public final SpeedController speedControllerStarboard = RobotMap.driveTrainSpeedControllerStarboard;
	private final VictorSPX speedControllerPortFollow = RobotMap.driveTrainSpeedControllerPortFollow;
	private final VictorSPX speedControllerStarboardFollow = RobotMap.driveTrainSpeedControllerStarFollow;
	// private final SpeedController speedController3 =
	// RobotMap.driveTrainSpeedController3;
	// private final SpeedController speedController4 =
	// RobotMap.driveTrainSpeedController4;
	private final DifferentialDrive robotDrive = RobotMap.driveTrainRobotDrive;
	public final Encoder encoderStarboard = RobotMap.driveTrainQuadratureEncoderStarboard;
	public final Encoder encoderPort = RobotMap.driveTrainQuadratureEncoderPort;
	// private final Encoder quadratureEncoder3 =
	// RobotMap.driveTrainQuadratureEncoder4;
	public final Solenoid gearShift = RobotMap.driveTrainSingleSolenoid;
	public boolean encoderPortFunctional, encoderStarboardFunctional; // set by POST.

	// private final Encoder quadratureEncoder4 =
	// RobotMap.driveTrainQuadrature
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public DriveTrain() {
		addChild(robotDrive);
		addChild((Sendable) speedControllerPort);
		LiveWindow.add((Sendable) speedControllerPort);
		addChild((Sendable) speedControllerStarboard);
		LiveWindow.add((Sendable) speedControllerStarboard);
	}

	// @Override
	public void initDefaultCommand() {
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		setDefaultCommand(new OIDrive());
	}

	@Override
	public void periodic() {
		// Put code here to be run every loop

	}

	public void arcadeDrive(Joystick joystick1, Joystick joystickIgnored) {// defines arcadeDrive for OI
		// double z = joystick1.getX() + joystick1.getTwist();
		// double x = joystick1.getY();
		// Please note: Grady had added this some time ago and it wasn't working.  I just fixed it.  Jack may yell at us for changing it.
		gearShift.set(Math.abs(joystick1.getY()) > .7);		//  If >70% speed, shift into high gear; if <=70% speed, shift into low gear
		
		/*
		 *  The arcadeDrive call parameters are (signed) speed and (signed) turn value [-1, 1]
		 *  Pushing the joystick forward to drive forward increases the joystick's Y parameter.  Even though the arcadeDrive calls this field "xSpeed", it comes from the Y axis of the joystick
		 *  Pushing the joystick left and right changes the joystick's X parameter.  Even though the arcadeDrive calls this field "zRotation", it comes from the X axis of the joystick.
		 */
		robotDrive.arcadeDrive(joystick1.getY(), -joystick1.getX() * Math.abs(joystick1.getX()), false);
		
	}

	public void tankAutoDrive(double speedLeft, double speedRight) {
		// double z = x + rotate;
		Robot.driveTrain.speedControllerPort.set(-speedLeft);
		Robot.driveTrain.speedControllerStarboard.set(speedRight);
		// robotDrive.arcadeDrive(-y, rotate, false);// TODO check math
	}
	// Put methods for controlling this subsystem
	// here. Call these from Commands.

	public void tankDrive(Joystick joystick1, Joystick joystick2) {// defines tankDrive
		robotDrive.tankDrive(-joystick1.getY() * Math.abs(joystick1.getY()),
				-joystick2.getY() * Math.abs(joystick2.getY()));
	}

	public void arcadeDrive(double forwardSpeed, double turnSpeed) {
		robotDrive.arcadeDrive(forwardSpeed, turnSpeed, false); // false here means do not square the inputs (if
																// omitted, the argument defaults to true)
	}

	public void curvatureDrive(double forwardSpeed, double turnRadius) {
		robotDrive.curvatureDrive(forwardSpeed, turnRadius, false);
	}
	
	/**
	 * Return the distance the robot has traveled in feet since the last call to
	 * {@link #reset Robot.driveTrain.reset()}, or robot program start, whichever
	 * was later. If the robot drove backwards, the value returned will be negative.
	 * If the robot spins in place, the value will not change.
	 * 
	 * DriveTrain.getDistance() also checks to ensure functionality of the encoders and throws
	 * an error to the console if both encoders are nonfunctional
	 * 
	 * @return the average of the left and right encoder values
	 */
	public double getDistance() {
		/*
    	 * A note on Encoders and the sign of distance:
    	 * Encoders will decrement when the roll backwards.  Therefore, if you want the robot to travel backwards during autonomous,
    	 * you must set BOTH the speed and the distance to a negative value (multiply by "BACKWARDS"
    	 */

		if (encoderPortFunctional && encoderStarboardFunctional)
			return (encoderStarboard.getDistance() + (-1 * encoderPort.getDistance()))/2;
		else if(encoderPortFunctional) {
			System.out.println("encoderPort NOT FUNCTIONAL");
			return -encoderPort.getDistance();
		}
		else if(encoderStarboardFunctional) {
			System.out.println("encoderStarboard NOT FUNCTIONAL");
			return encoderStarboard.getDistance();
		}
		else {
			System.out.println("Both Encoders NOT FUNCTIONAL");
			return (encoderStarboard.getDistance() + (-1 * encoderPort.getDistance()))/2;
		}
	}

	/**getDistance
	 * Reset both encoders, restoring the value returned by getDistance() to zero.
	 */
	public void reset() {
		encoderStarboard.reset();
		encoderPort.reset();
	}

	public void setBrakeCoast(NeutralMode b) {
		((VictorSPX) speedControllerPort).setNeutralMode(b);
		((VictorSPX) speedControllerStarboard).setNeutralMode(b);
		speedControllerPortFollow.setNeutralMode(b);
		speedControllerStarboardFollow.setNeutralMode(b);
		
	}
}