// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.Robot2018.subsystems;

import org.usfirst.frc2813.Robot2018.RobotMap;
import com.ctre.phoenix.motorcontrol.can.TalonSRX;

import edu.wpi.first.wpilibj.command.Subsystem;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Elevator extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	public final TalonSRX speedController = RobotMap.srxElevator;
    // last argument speedController = normal operation, last argument this::debugPrintPIDOutput = debug mode.
    public boolean encoderFunctional;
    
    public Elevator() {
    	//encoder.setIndexSource(limitSwitch); //TODO - REMOVE: TAKEN CARE OF BY TALON SRX this makes the encoder self-reset when the limit switch is pressed, at the FPGA level.
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /*CURRENTLY NOT USED ANYWHERE  -- TODO? REMOVE
     * public void debugPrintPIDOutput(double pidOutput) {
		System.out.println("Output updated to: "+pidOutput);
		speedController.pidWrite(pidOutput);
	}*/
    
    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MaintainElevatorPosition());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
    	
    	//if(getCurrentCommand() == null) {
    		//new MaintainElevatorPosition().start();
    	//}
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

