// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2813.Robot2018.commands;
import org.usfirst.frc2813.logging.Logger;

import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.command.InstantCommand;

/**
 *
 */
public class ToggleSolenoidGeneral extends InstantCommand {
	/**
	 * Switch the position of the intake pistons
	 */
	private final Solenoid solenoid;

    public ToggleSolenoidGeneral(Solenoid solenoid) {
    	this.solenoid = solenoid;
    }

	//@Override
	protected void initialize() {
		super.initialize();
        boolean old = solenoid.get();
        Logger.info(this + " toggling " + solenoid + " from " + old + " to " + !old);
        solenoid.set(!old);
	}

    public String toString() {
        return "ToggleSolenoidGeneral(" + solenoid + ")";
    }
}

